#include <stdio.h>

int main()
{
	/* constants */
	const int YEAR = 2019;
	const char BASIC_INFO[] = "기본 정보";
	const char NAME[] = "이름";
	const char NATIONALITY[] = "국적";
	const char TEAM[] = "소속팀";
	const char PREFFERRED_FOOT[] = "선호하는 발";
	const char HEIGHT[] = "키";
	const char WEIGHT[] = "몸무게";
	const char WAGE[] = "주급";
	const char VALUE[] = "가치";
	const char TECHNICAL[] = "기술적 능력";
	const char MENTAL[] = "정신적 능력";
	const char PHYSICAL[] = "신체적 능력";
	const char CORNERS[] = "코너킥";
	const char CROSSING[] = "크로스";
	const char DRIBBLING[] = "드리블";
	const char FINISHING[] = "골 결정력";
	const char FIRST_TOUCH[] = "퍼스트터치";
	const char FREE_KICK_TAKING[] = "프리킥";
	const char HEADING[] = "헤딩";
	const char LONG_SHOTS[] = "중거리 슛";
	const char LONG_THROWS[] = "장거리 스로인";
	const char MARKING[] = "일대일마크";
	const char PASSING[] = "패스";
	const char PENALTY_TAKING[] = "패널티킥";
	const char TACKLING[] = "태클";
	const char TECHNIQUE[] = "개인기";
	const char AGGRESSION[] = "적극성";
	const char ANTICIPATION[] = "예측력";
	const char BRAVERY[] = "대담함";
	const char COMPOSURE[] = "침착함";
	const char CONCENTRATION[] = "집중력";
	const char DECISIONS[] = "판단력";
	const char DETERMINATIONS[] = "승부욕";
	const char FLAIR[] = "천재성";
	const char LEADERSHIP[] = "리더십";
	const char OFF_THE_BALL[] = "공격위치선정";
	const char POSITIONING[] = "수비위치선정";
	const char TEAMWORK[] = "팀워크";
	const char VISION[] = "시야";
	const char WORK_RATE[] = "활동량";
	const char ACCELERATION[] = "순간속도";
	const char AGILITY[] = "민첩성";
	const char BALANCE[] = "균형감각";
	const char JUMPING_REACH[] = "점프거리";
	const char NATURAL_FITNESS[] = "타고난 체력";
	const char PACE[] = "주력";
	const char STAMINA[] = "지구력";
	const char STRENGTH[] = "몸싸움";

	/* Basic Info */
	char nameA[16], nameB[16];
	char nationalityA[16], nationalityB[16];
	char teamA[16], teamB[16];
	char prefferredFootA[16], prefferredFootB[16];
	double heightA, heightB;
	double weightA, weightB;
	long long wageA, wageB;
	long long valueA, valueB;

	/* Technical */
	int cornersA, cornersB;
	int crossingA, crossingB;
	int dribblingA, dribblingB;
	int finishingA, finishingB;
	int firstTouchA, firstTouchB;
	int freeKickTakingA, freeKickTakingB;
	int headingA, headingB;
	int longShotsA, longShotsB;
	int longThrowsA, longThrowsB;
	int markingA, markingB;
	int passingA, passingB;
	int penaltyTakingA, penaltyTakingB;
	int tacklingA, tacklingB;
	int techniqueA, techniqueB;

	/* Mental */
	int aggressionA, aggressionB;
	int anticipationA, anticipationB;
	int braveryA, braveryB;
	int composureA, composureB;
	int concentrationA, concentrationB;
	int decisionsA, decisionsB;
	int determinationA, determinationB;
	int flairA, flairB;
	int leadershipA, leadershipB;
	int offTheBallA, offTheBallB;
	int positioningA, positioningB;
	int teamworkA, teamworkB;
	int visionA, visionB;
	int workRateA, workRateB;

	/* Physical */
	int accelerationA, accelerationB;
	int agilityA, agilityB;
	int balanceA, balanceB;
	int jumpingReachA, jumpingReachB;
	int naturalFitnessA, naturalFitnessB;
	int paceA, paceB;
	int staminaA, staminaB;
	int strengthA, strengthB;

	printf("  _____           _   _           _ _   ____                  _   \n");
	printf(" |  ___|__   ___ | |_| |__   __ _| | | / ___|  ___ ___  _   _| |_ \n");
	printf(" | |_ / _ \\ / _ \\| __| '_ \\ / _` | | | \\___ \\ / __/ _ \\| | | | __| \n");
	printf(" |  _| (_) | (_) | |_| |_) | (_| | | |  ___) | (_| (_) | |_| | |_ \n");
	printf(" |_|  \\___/ \\___/ \\__|_.__/ \\__,_|_|_| |____/ \\___\\___/ \\__,_|\\__|  ");
	printf("%d\n", YEAR);
	printf("  FS%d는 두 선수의 능력치를 비교해서 보여주고 분석합니다.\n\n", YEAR);

	printf("--%s--\n", BASIC_INFO);
	printf("%s>>", NAME);
	scanf("%s", nameA);
	printf("%s>>", NATIONALITY);
	scanf("%s", nationalityA);
	printf("%s>>", TEAM);
	scanf("%s", teamA);
	printf("%s(R,L))>>", PREFFERRED_FOOT);
	scanf("%s", prefferredFootA);
	printf("%s>>", HEIGHT);
	scanf("%lf", &heightA);
	printf("%s>>", WEIGHT);
	scanf("%lf", &weightA);
	printf("%s>>", WAGE);
	scanf("%lld", &wageA);
	printf("%s>>", VALUE);
	scanf("%lld", &valueA);

	printf("--%s--\n", TECHNICAL);
	printf("%s>>", CORNERS);
	scanf("%d", &cornersA);
	printf("%s>>", CROSSING);
	scanf("%d", &crossingA);
	printf("%s>>", DRIBBLING);
	scanf("%d", &dribblingA);
	printf("%s>>", FINISHING);
	scanf("%d", &finishingA);
	printf("%s>>", FIRST_TOUCH);
	scanf("%d", &firstTouchA);
	printf("%s>>", FREE_KICK_TAKING);
	scanf("%d", &freeKickTakingA);
	printf("%s>>", HEADING);
	scanf("%d", &headingA);
	printf("%s>>", LONG_SHOTS);
	scanf("%d", &longShotsA);
	printf("%s>>", LONG_THROWS);
	scanf("%d", &longThrowsA);
	printf("%s>>", MARKING);
	scanf("%d", &markingA);
	printf("%s>>", PASSING);
	scanf("%d", &passingA);
	printf("%s>>", PENALTY_TAKING);
	scanf("%d", &penaltyTakingA);
	printf("%s>>", TACKLING);
	scanf("%d", &tacklingA);
	printf("%s>>", TECHNIQUE);
	scanf("%d", &techniqueA);

	printf("--%s--\n", MENTAL);
	printf("%s>>", AGGRESSION);
	scanf("%d", &aggressionA);
	printf("%s>>", ANTICIPATION);
	scanf("%d", &anticipationA);
	printf("%s>>", BRAVERY);
	scanf("%d", &braveryA);
	printf("%s>>", COMPOSURE);
	scanf("%d", &composureA);
	printf("%s>>", CONCENTRATION);
	scanf("%d", &concentrationA);
	printf("%s>>", DECISIONS);
	scanf("%d", &decisionsA);
	printf("%s>>", DETERMINATIONS);
	scanf("%d", &determinationA);
	printf("%s>>", FLAIR);
	scanf("%d", &flairA);
	printf("%s>>", LEADERSHIP);
	scanf("%d", &leadershipA);
	printf("%s>>", OFF_THE_BALL);
	scanf("%d", &offTheBallA);
	printf("%s>>", POSITIONING);
	scanf("%d", &positioningA);
	printf("%s>>", TEAMWORK);
	scanf("%d", &teamworkA);
	printf("%s>>", VISION);
	scanf("%d", &visionA);
	printf("%s>>", WORK_RATE);
	scanf("%d", &workRateA);

	printf("--%s--\n", PHYSICAL);
	printf("%s>>", ACCELERATION);
	scanf("%d", &accelerationA);
	printf("%s>>", AGILITY);
	scanf("%d", &agilityA);
	printf("%s>>", BALANCE);
	scanf("%d", &balanceA);
	printf("%s>>", JUMPING_REACH);
	scanf("%d", &jumpingReachA);
	printf("%s>>", NATURAL_FITNESS);
	scanf("%d", &naturalFitnessA);
	printf("%s>>", PACE);
	scanf("%d", &paceA);
	printf("%s>>", STAMINA);
	scanf("%d", &staminaA);
	printf("%s>>", STRENGTH);
	scanf("%d", &strengthA);

	printf("%s 선수 정보 입력 완료\n\n", nameA);

	printf("--%s--\n", BASIC_INFO);
	printf("%s>>", NAME);
	scanf("%s", nameB);
	printf("%s>>", NATIONALITY);
	scanf("%s", nationalityB);
	printf("%s>>", TEAM);
	scanf("%s", teamB);
	printf("%s(R,L))>>", PREFFERRED_FOOT);
	scanf("%s", prefferredFootB);
	printf("%s>>", HEIGHT);
	scanf("%lf", &heightB);
	printf("%s>>", WEIGHT);
	scanf("%lfs", &weightB);
	printf("%s>>", WAGE);
	scanf("%lld", &wageB);
	printf("%s>>", VALUE);
	scanf("%lld", &valueB);

	printf("--%s--\n", TECHNICAL);
	printf("%s>>", CORNERS);
	scanf("%d", &cornersB);
	printf("%s>>", CROSSING);
	scanf("%d", &crossingB);
	printf("%s>>", DRIBBLING);
	scanf("%d", &dribblingB);
	printf("%s>>", FINISHING);
	scanf("%d", &finishingB);
	printf("%s>>", FIRST_TOUCH);
	scanf("%d", &firstTouchB);
	printf("%s>>", FREE_KICK_TAKING);
	scanf("%d", &freeKickTakingB);
	printf("%s>>", HEADING);
	scanf("%d", &headingB);
	printf("%s>>", LONG_SHOTS);
	scanf("%d", &longShotsB);
	printf("%s>>", LONG_THROWS);
	scanf("%d", &longThrowsB);
	printf("%s>>", MARKING);
	scanf("%d", &markingB);
	printf("%s>>", PASSING);
	scanf("%d", &passingB);
	printf("%s>>", PENALTY_TAKING);
	scanf("%d", &penaltyTakingB);
	printf("%s>>", TACKLING);
	scanf("%d", &tacklingB);
	printf("%s>>", TECHNIQUE);
	scanf("%d", &techniqueB);

	printf("--%s--\n", MENTAL);
	printf("%s>>", AGGRESSION);
	scanf("%d", &aggressionB);
	printf("%s>>", ANTICIPATION);
	scanf("%d", &anticipationB);
	printf("%s>>", BRAVERY);
	scanf("%d", &braveryB);
	printf("%s>>", COMPOSURE);
	scanf("%d", &composureB);
	printf("%s>>", CONCENTRATION);
	scanf("%d", &concentrationB);
	printf("%s>>", DECISIONS);
	scanf("%d", &decisionsB);
	printf("%s>>", DETERMINATIONS);
	scanf("%d", &determinationB);
	printf("%s>>", FLAIR);
	scanf("%d", &flairB);
	printf("%s>>", LEADERSHIP);
	scanf("%d", &leadershipB);
	printf("%s>>", OFF_THE_BALL);
	scanf("%d", &offTheBallB);
	printf("%s>>", POSITIONING);
	scanf("%d", &positioningB);
	printf("%s>>", TEAMWORK);
	scanf("%d", &teamworkB);
	printf("%s>>", VISION);
	scanf("%d", &visionB);
	printf("%s>>", WORK_RATE);
	scanf("%d", &workRateB);

	printf("--%s--\n", PHYSICAL);
	printf("%s>>", ACCELERATION);
	scanf("%d", &accelerationB);
	printf("%s>>", AGILITY);
	scanf("%d", &agilityB);
	printf("%s>>", BALANCE);
	scanf("%d", &balanceB);
	printf("%s>>", JUMPING_REACH);
	scanf("%d", &jumpingReachB);
	printf("%s>>", NATURAL_FITNESS);
	scanf("%d", &naturalFitnessB);
	printf("%s>>", PACE);
	scanf("%d", &paceB);
	printf("%s>>", STAMINA);
	scanf("%d", &staminaB);
	printf("%s>>", STRENGTH);
	scanf("%d", &strengthB);

	printf("%s 선수 정보 입력 완료\n\n", nameB);

	/* sum of A*/
	int sumTechnicalA = cornersA + crossingA + dribblingA + finishingA + firstTouchA + freeKickTakingA + headingA + longShotsA + longThrowsA + markingA + passingA + penaltyTakingA + tacklingA + techniqueA;
	int sumMentalA = aggressionA + anticipationA + braveryA + composureA + concentrationA + decisionsA + determinationA + flairA + leadershipA + offTheBallA + positioningA + teamworkA + visionA + workRateA;
	int sumPhysicalA = accelerationA + agilityA + balanceA + jumpingReachA + naturalFitnessA + paceA + staminaA + strengthA;
	/* sum of B */
	int sumTechnicalB = cornersB + crossingB + dribblingB + finishingB + firstTouchB + freeKickTakingB + headingB + longShotsB + longThrowsB + markingB + passingB + penaltyTakingB + tacklingB + techniqueB;
	int sumMentalB = aggressionB + anticipationB + braveryB + composureB + concentrationB + decisionsB + determinationB + flairB + leadershipB + offTheBallB + positioningB + teamworkB + visionB + workRateB;
	int sumPhysicalB = accelerationB + agilityB + balanceB + jumpingReachB + naturalFitnessB + paceB + staminaB + strengthB;

	/* basic info */
	printf("_________________________________________________________________\n");
	printf("%13s\t|%15s\t\t%15s\n", NAME, nameA, nameB);
	printf("%13s\t|%15s\t\t%15s\n", NATIONALITY, nationalityA, nationalityB);
	printf("%14s\t|%15s\t\t%15s\n", TEAM, teamA, teamB);
	printf("%12s\t|%13.1lfcm\t\t%13.1lfcm\n", HEIGHT, heightA, heightB);
	printf("%14s\t|%13.1lfkg\t\t%13.1lfkg\n", WEIGHT, weightA, weightB);
	printf("%12s\t|%15s\t\t%15s\n", PREFFERRED_FOOT, prefferredFootA, prefferredFootB);
	printf("─────────────────────────────────────────────────────────────────\n");
	/* result */
	printf("___________________분석 결과 (0:false, 1:true)___________________\n\n");
	printf("%s 선수가 %s 선수보다 %s이(가) 더 높다 : %d\n", nameA, nameB, WAGE, (wageA > wageB));
	printf("%s 선수가 %s 선수보다 %s이(가) 더 높다 : %d\n", nameA, nameB, VALUE, (valueA > valueB));
	printf("%s 선수가 %s 선수보다 %s이(가) 더 높다 : %d\n", nameA, nameB, TECHNICAL, (sumTechnicalA > sumTechnicalB));
	printf("%s 선수가 %s 선수보다 %s이(가) 더 높다 : %d\n", nameA, nameB, MENTAL, (sumMentalA > sumMentalB));
	printf("%s 선수가 %s 선수보다 %s이(가) 더 높다 : %d\n", nameA, nameB, PHYSICAL, (sumPhysicalA > sumPhysicalB));
	printf("─────────────────────────────────────────────────────────────────\n");

	return 0;
}

